version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wordle_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: wordle_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      JWT_SECRET: superkey
      WORD_GAME_SEED: 123456
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: wordle_front
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata: